import 'package:firepath/models/career_goal.dart';
import 'package:firepath/models/requirement.dart';
import 'package:firepath/models/resource.dart';

/// A starter, reusable dataset of *typical* fire/EMS career paths.
///
/// This is intentionally NOT a legal/official source of truth.
/// Departments and states vary.
class FireOpsCatalog {
  static const List<String> usStates = [
    'AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY',
  ];

  static const List<String> commonRoles = [
    'Exploring the Fire Service',
    'Fire Academy / Recruit',
    'Volunteer Firefighter',
    'Firefighter',
    'Firefighter / EMT',
    'Firefighter / Paramedic',
    'Driver / Engineer',
    'Lieutenant',
    'Captain',
    'Chief Officer',
    'EMT',
    'Paramedic',
    'Fire Inspector',
    'Fire Instructor',
    'Other / Custom',
  ];

  static const List<String> commonCertifications = [
    'High school diploma or GED',
    "Valid driver's license",
    'CPR/BLS',
    'EMT',
    'Advanced EMT',
    'Paramedic',
    'Fire academy',
    'CPAT / physical ability test',
    'Firefighter I',
    'Firefighter II',
    'Hazardous Materials Awareness',
    'Hazardous Materials Operations',
    'Driver Operator – Pumper',
    'Driver Operator – Aerial',
    'EVOC / Emergency Vehicle Driver Training',
    'Pump operations training',
    'Apparatus driving fundamentals',
    'Fire Officer I',
    'Fire Officer II',
    'Fire Officer III',
    'Fire Officer IV',
    'Fire Instructor I',
    'Fire Instructor II',
    'Fire Inspector I',
    'Fire Inspector II',
    'Plans Examiner',
    'Fire Investigator',
    'ICS-100',
    'ICS-200',
    'ICS-300',
    'ICS-400',
    'IS-700',
    'IS-800',
    'ACLS',
    'PALS',
    'PHTLS',
    'ITLS',
    'AMLS',
    'EPC',
  ];

  /// Soft prerequisite relationships (recommended ordering; not universal).
  static const Map<String, List<String>> certificationPrerequisites = {
    'Firefighter II': ['Firefighter I'],
    'Hazardous Materials Operations': ['Hazardous Materials Awareness'],
    'Fire Officer II': ['Fire Officer I'],
    'Fire Officer III': ['Fire Officer II'],
    'Fire Officer IV': ['Fire Officer III'],
    'Fire Instructor II': ['Fire Instructor I'],
    'Driver Operator – Aerial': ['Apparatus driving fundamentals'],
    'Driver Operator – Pumper': ['Apparatus driving fundamentals'],
    'Advanced EMT': ['EMT'],
    'Paramedic': ['EMT'],
  };

  static List<CareerGoal> goals() {
    final now = DateTime.now();

    Requirement req({
      required String id,
      required String name,
      required String description,
      required String category,
      required RequirementPriority priority,
      required RequirementType type,
      required RequirementSource source,
      bool defaultRequired = true,
      bool stateDependent = false,
      bool departmentDependent = false,
      double? experienceValue,
      String? experienceUnit,
      double? progressRequired,
      String? progressUnit,
      String? certRef,
      List<String> resourceIds = const [],
      int sortOrder = 0,
      int? estimatedDurationDays,
      int? recommendedLeadTimeDays,
      bool canRunConcurrent = true,
      TimelineCategory? timelineCategory,
    }) {
      final prereqs = certificationPrerequisites[certRef ?? name] ?? const <String>[];
      return Requirement(
        id: id,
        name: name,
        category: category,
        priority: priority,
        description: description,
        type: type,
        requirementSource: source,
        defaultRequired: defaultRequired,
        stateDependent: stateDependent,
        departmentDependent: departmentDependent,
        completed: false,
        progressCurrent: type == RequirementType.numericProgress ? 0 : null,
        progressRequired: type == RequirementType.numericProgress ? (progressRequired ?? 0) : null,
        progressUnit: type == RequirementType.numericProgress ? (progressUnit ?? 'hours') : null,
        experienceValue: type == RequirementType.experience ? experienceValue : null,
        experienceUnit: type == RequirementType.experience ? (experienceUnit ?? 'years') : null,
        certificationReference: certRef,
        prerequisiteRequirementIds: prereqs,
        resourceIds: resourceIds,
        resourceLinks: const [],
        sortOrder: sortOrder,

        estimatedDurationDays: estimatedDurationDays,
        recommendedLeadTimeDays: recommendedLeadTimeDays,
        canRunConcurrent: canRunConcurrent,
        timelineCategory: timelineCategory,
        suggestedStartDate: null,
        suggestedCompletionDate: null,
        createdAt: now,
        updatedAt: now,
      );
    }

    // NOTE: This starter catalog is intentionally expandable. Career requirements vary
    // widely across departments and states.

    // OPERATIONS PATH
    final opsEntry = CareerGoal(
      id: 'ops_entry',
      title: 'Entry / Recruit',
      category: 'Operations',
      description: 'A typical starting checklist before or during recruit/academy.',
      subtitle: 'Recruit → Firefighter',
      typicalPrerequisiteRoles: const ['Exploring the Fire Service'],
      requirements: [
        req(
          id: 'ops_entry_ged',
          name: 'High school diploma or GED',
          description: 'Often required for hiring; may be verified during recruitment.',
          category: 'Eligibility',
          priority: RequirementPriority.core,
          type: RequirementType.custom,
          source: RequirementSource.commonlyRequired,
          departmentDependent: true,
          sortOrder: 10,
        ),
        req(
          id: 'ops_entry_license',
          name: "Valid driver's license",
          description: 'Common requirement for employment and driving apparatus/POV response.',
          category: 'Eligibility',
          priority: RequirementPriority.core,
          type: RequirementType.custom,
          source: RequirementSource.commonlyRequired,
          departmentDependent: true,
          sortOrder: 20,
        ),
        req(
          id: 'ops_entry_cpr',
          name: 'CPR/BLS',
          description: 'Basic life support; common for both fire and EMS response.',
          category: 'Medical',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'CPR/BLS',
          sortOrder: 30,
        ),
        req(
          id: 'ops_entry_emt',
          name: 'EMT',
          description: 'Recommended or required in many departments; varies widely.',
          category: 'Medical',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          stateDependent: true,
          departmentDependent: true,
          certRef: 'EMT',
          sortOrder: 40,
        ),
        req(
          id: 'ops_entry_cpat',
          name: 'CPAT / physical ability test',
          description: 'Many agencies use CPAT or a local physical ability test.',
          category: 'Fitness',
          priority: RequirementPriority.core,
          type: RequirementType.custom,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 50,
        ),
        req(
          id: 'ops_entry_academy',
          name: 'Fire academy',
          description: 'Academy completion may be required before assignment to operations.',
          category: 'Training',
          priority: RequirementPriority.core,
          type: RequirementType.trainingCourse,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 60,
        ),
        req(
          id: 'ops_entry_ff1',
          name: 'Firefighter I',
          description: 'Entry-level structural firefighting certification (often required).',
          category: 'Fire',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Firefighter I',
          sortOrder: 70,
        ),
        req(
          id: 'ops_entry_haz_aw',
          name: 'Hazardous Materials Awareness',
          description: 'Entry hazmat awareness level.',
          category: 'HazMat',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Hazardous Materials Awareness',
          sortOrder: 80,
        ),
        req(
          id: 'ops_entry_haz_ops',
          name: 'Hazardous Materials Operations',
          description: 'Operations-level hazmat response; common baseline.',
          category: 'HazMat',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Hazardous Materials Operations',
          sortOrder: 90,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['Firefighter'],
      createdAt: now,
      updatedAt: now,
    );

    // VOLUNTEER FIREFIGHTER (first-class starting point)
    final volunteerFirefighter = CareerGoal(
      id: 'ops_volunteer_firefighter',
      title: 'Volunteer Firefighter',
      category: 'Volunteer',
      description: 'Typical operational baseline for volunteer firefighters. Your training and experience may exceed these items — FireOps Path will credit what you already have.',
      subtitle: 'Volunteer development or transition to career',
      typicalPrerequisiteRoles: const ['Exploring the Fire Service', 'Fire Academy / Recruit'],
      requirements: [
        req(
          id: 'vol_ff_license',
          name: "Valid driver's license",
          description: 'Common requirement for response and driving (department dependent).',
          category: 'Eligibility',
          priority: RequirementPriority.core,
          type: RequirementType.custom,
          source: RequirementSource.commonlyRequired,
          departmentDependent: true,
          sortOrder: 10,
        ),
        req(
          id: 'vol_ff_cpr',
          name: 'CPR/BLS',
          description: 'Common baseline for medical response.',
          category: 'Medical',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'CPR/BLS',
          sortOrder: 20,
        ),
        req(
          id: 'vol_ff_ff1',
          name: 'Firefighter I',
          description: 'Entry structural firefighter certification (common baseline).',
          category: 'Fire',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Firefighter I',
          sortOrder: 30,
        ),
        req(
          id: 'vol_ff_haz_ops',
          name: 'Hazardous Materials Operations',
          description: 'Operations-level HazMat is a common baseline for responders.',
          category: 'HazMat',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Hazardous Materials Operations',
          sortOrder: 40,
        ),
        req(
          id: 'vol_ff_ics200',
          name: 'ICS-200',
          description: 'Common incident management baseline (versions and acceptance vary).',
          category: 'ICS/NIMS',
          priority: RequirementPriority.recommended,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          departmentDependent: true,
          sortOrder: 50,
        ),
        req(
          id: 'vol_ff_emtrec',
          name: 'EMT',
          description: 'Recommended in many systems; not universal for volunteer fire.',
          category: 'Medical',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          stateDependent: true,
          departmentDependent: true,
          certRef: 'EMT',
          sortOrder: 60,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['Driver / Engineer', 'Lieutenant', 'Captain', 'Chief Officer', 'Career Firefighter'],
      createdAt: now,
      updatedAt: now,
    );

    // CAREER FIREFIGHTER (transition-friendly)
    final careerFirefighter = CareerGoal(
      id: 'ops_career_firefighter',
      title: 'Career Firefighter',
      category: 'Operations',
      description: 'A typical hiring + readiness checklist for a career firefighter role. Departments vary — mark items “Not required by my department” where appropriate.',
      subtitle: 'Volunteer / EMT → Career Firefighter',
      typicalPrerequisiteRoles: const ['Exploring the Fire Service', 'Fire Academy / Recruit', 'Volunteer Firefighter', 'EMT', 'Paramedic'],
      requirements: [
        req(
          id: 'career_ff_ff1',
          name: 'Firefighter I',
          description: 'Commonly required; sometimes completed during academy.',
          category: 'Fire',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Firefighter I',
          sortOrder: 10,
        ),
        req(
          id: 'career_ff_haz_ops',
          name: 'Hazardous Materials Operations',
          description: 'Commonly required baseline for responders.',
          category: 'HazMat',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Hazardous Materials Operations',
          sortOrder: 20,
        ),
        req(
          id: 'career_ff_cpr',
          name: 'CPR/BLS',
          description: 'Commonly required baseline.',
          category: 'Medical',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'CPR/BLS',
          sortOrder: 30,
        ),
        req(
          id: 'career_ff_license',
          name: "Valid driver's license",
          description: 'Common hiring requirement (department dependent).',
          category: 'Eligibility',
          priority: RequirementPriority.core,
          type: RequirementType.custom,
          source: RequirementSource.commonlyRequired,
          departmentDependent: true,
          sortOrder: 40,
        ),
        req(
          id: 'career_ff_ff2',
          name: 'Firefighter II',
          description: 'Often recommended; sometimes required before promotion.',
          category: 'Fire',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'Firefighter II',
          sortOrder: 50,
        ),
        req(
          id: 'career_ff_emt',
          name: 'EMT',
          description: 'Commonly recommended or required depending on system.',
          category: 'Medical',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          stateDependent: true,
          departmentDependent: true,
          certRef: 'EMT',
          sortOrder: 60,
        ),
        req(
          id: 'career_ff_ics',
          name: 'ICS / NIMS courses',
          description: 'Commonly recommended (ICS-100/200/700/800).',
          category: 'ICS/NIMS',
          priority: RequirementPriority.recommended,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          departmentDependent: true,
          sortOrder: 70,
        ),
        // Hiring process (department dependent)
        req(
          id: 'career_ff_application',
          name: 'Application',
          description: 'Department hiring process step.',
          category: 'Hiring process',
          priority: RequirementPriority.department,
          type: RequirementType.custom,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 100,
        ),
        req(
          id: 'career_ff_written',
          name: 'Written test',
          description: 'Department hiring process step.',
          category: 'Hiring process',
          priority: RequirementPriority.department,
          type: RequirementType.promotionalTest,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 110,
        ),
        req(
          id: 'career_ff_cpat',
          name: 'CPAT / Physical Ability Test',
          description: 'Physical ability / CPAT requirement (department dependent).',
          category: 'Hiring process',
          priority: RequirementPriority.department,
          type: RequirementType.practical,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 120,
        ),
        req(
          id: 'career_ff_oral',
          name: 'Oral board / interview',
          description: 'Department hiring process step.',
          category: 'Hiring process',
          priority: RequirementPriority.department,
          type: RequirementType.interview,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 130,
        ),
        req(
          id: 'career_ff_background',
          name: 'Background investigation',
          description: 'Department hiring process step.',
          category: 'Hiring process',
          priority: RequirementPriority.department,
          type: RequirementType.custom,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 140,
        ),
        req(
          id: 'career_ff_medical',
          name: 'Medical evaluation',
          description: 'Department hiring process step.',
          category: 'Hiring process',
          priority: RequirementPriority.department,
          type: RequirementType.custom,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 150,
        ),
        req(
          id: 'career_ff_psych',
          name: 'Psychological evaluation',
          description: 'Department hiring process step.',
          category: 'Hiring process',
          priority: RequirementPriority.department,
          type: RequirementType.custom,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 160,
        ),
        req(
          id: 'career_ff_academy',
          name: 'Fire academy',
          description: 'Department academy or equivalent completion.',
          category: 'Hiring process',
          priority: RequirementPriority.department,
          type: RequirementType.trainingCourse,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 170,
        ),
        req(
          id: 'career_ff_probation',
          name: 'Probation',
          description: 'Department probationary period requirements.',
          category: 'Hiring process',
          priority: RequirementPriority.department,
          type: RequirementType.custom,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 180,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['Engineer / Driver Operator', 'Lieutenant'],
      createdAt: now,
      updatedAt: now,
    );

    final firefighter = CareerGoal(
      id: 'ops_firefighter',
      title: 'Firefighter',
      category: 'Operations',
      description: 'Common baseline requirements for a firefighter role.',
      subtitle: 'Entry / Recruit → Firefighter',
      typicalPrerequisiteRoles: const ['Entry / Recruit', 'Fire academy'],
      requirements: [
        req(
          id: 'ops_ff_ff1',
          name: 'Firefighter I',
          description: 'Often required for operations assignment.',
          category: 'Fire',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Firefighter I',
          sortOrder: 10,
        ),
        req(
          id: 'ops_ff_haz_ops',
          name: 'Hazardous Materials Operations',
          description: 'Common baseline for hazmat response.',
          category: 'HazMat',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Hazardous Materials Operations',
          sortOrder: 20,
        ),
        req(
          id: 'ops_ff_cpr',
          name: 'CPR/BLS',
          description: 'Basic life support credential.',
          category: 'Medical',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'CPR/BLS',
          sortOrder: 30,
        ),
        req(
          id: 'ops_ff_license',
          name: "Valid driver's license",
          description: 'Often required as a condition of employment.',
          category: 'Eligibility',
          priority: RequirementPriority.core,
          type: RequirementType.custom,
          source: RequirementSource.commonlyRequired,
          departmentDependent: true,
          sortOrder: 40,
        ),
        req(
          id: 'ops_ff_ff2',
          name: 'Firefighter II',
          description: 'Advanced firefighter certification (commonly recommended).',
          category: 'Fire',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'Firefighter II',
          sortOrder: 50,
        ),
        req(
          id: 'ops_ff_emt',
          name: 'EMT',
          description: 'Commonly recommended or required; depends on department and state.',
          category: 'Medical',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          stateDependent: true,
          departmentDependent: true,
          certRef: 'EMT',
          sortOrder: 60,
        ),
        req(
          id: 'ops_ff_ics100',
          name: 'ICS-100',
          description: 'Intro to incident command.',
          category: 'Command',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'ICS-100',
          sortOrder: 70,
        ),
        req(
          id: 'ops_ff_ics200',
          name: 'ICS-200',
          description: 'Intermediate incident command principles.',
          category: 'Command',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'ICS-200',
          sortOrder: 80,
        ),
        req(
          id: 'ops_ff_is700',
          name: 'IS-700',
          description: 'NIMS introductory course (often used in many agencies).',
          category: 'Command',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'IS-700',
          sortOrder: 90,
        ),
        req(
          id: 'ops_ff_is800',
          name: 'IS-800',
          description: 'National response framework overview (commonly used).',
          category: 'Command',
          priority: RequirementPriority.development,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'IS-800',
          sortOrder: 100,
        ),
        req(
          id: 'ops_ff_academy_dept',
          name: 'Fire academy completion',
          description: 'May be required by your department or state.',
          category: 'Training',
          priority: RequirementPriority.department,
          type: RequirementType.trainingCourse,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 110,
        ),
        req(
          id: 'ops_ff_prob',
          name: 'Probationary task book / skills sign-off',
          description: 'Commonly used by departments to document probationary competency.',
          category: 'Department',
          priority: RequirementPriority.department,
          type: RequirementType.taskBook,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 120,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['Engineer / Driver Operator', 'Lieutenant'],
      createdAt: now,
      updatedAt: now,
    );

    final engineer = CareerGoal(
      id: 'ops_engineer',
      title: 'Engineer / Driver Operator',
      category: 'Operations',
      description: 'Typical preparation for engineer/driver operator responsibilities.',
      subtitle: 'Firefighter → Engineer',
      typicalPrerequisiteRoles: const ['Firefighter'],
      requirements: [
        req(
          id: 'ops_eng_ff1',
          name: 'Firefighter I',
          description: 'Most engineer roles require baseline firefighter certification.',
          category: 'Fire',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Firefighter I',
          sortOrder: 10,
        ),
        req(
          id: 'ops_eng_ff2',
          name: 'Firefighter II',
          description: 'Often required or strongly recommended before promotion.',
          category: 'Fire',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          departmentDependent: true,
          certRef: 'Firefighter II',
          sortOrder: 20,
        ),
        req(
          id: 'ops_eng_haz_ops',
          name: 'Hazardous Materials Operations',
          description: 'Common baseline credential.',
          category: 'HazMat',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Hazardous Materials Operations',
          sortOrder: 30,
        ),
        req(
          id: 'ops_eng_license',
          name: "Valid driver's license",
          description: 'Often required; may include additional endorsements based on apparatus.',
          category: 'Eligibility',
          priority: RequirementPriority.core,
          type: RequirementType.custom,
          source: RequirementSource.commonlyRequired,
          departmentDependent: true,
          sortOrder: 40,
        ),
        req(
          id: 'ops_eng_fundamentals',
          name: 'Apparatus driving fundamentals',
          description: 'Driver training program covering safe operations and policy.',
          category: 'Driving',
          priority: RequirementPriority.core,
          type: RequirementType.trainingCourse,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 50,
        ),
        req(
          id: 'ops_eng_evoc',
          name: 'EVOC / Emergency Vehicle Driver Training',
          description: 'Emergency vehicle operations course (often used).',
          category: 'Driving',
          priority: RequirementPriority.recommended,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          departmentDependent: true,
          sortOrder: 60,
        ),
        req(
          id: 'ops_eng_driver_pumper',
          name: 'Driver Operator – Pumper',
          description: 'Operate and pump fire apparatus safely and effectively.',
          category: 'Driving',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Driver Operator – Pumper',
          resourceIds: const ['fireops_calc', 'firepumpsim'],
          sortOrder: 70,
        ),
        req(
          id: 'ops_eng_driver_aerial',
          name: 'Driver Operator – Aerial',
          description: 'Operate aerial devices and set up safely on scene.',
          category: 'Driving',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          departmentDependent: true,
          certRef: 'Driver Operator – Aerial',
          resourceIds: const ['fireops_calc', 'firepumpsim'],
          sortOrder: 80,
        ),
        req(
          id: 'ops_eng_pump_ops',
          name: 'Pump operations training',
          description: 'Hands-on pumping, drafting, pressure management, and troubleshooting.',
          category: 'Pump',
          priority: RequirementPriority.recommended,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          resourceIds: const ['fireops_calc', 'firepumpsim'],
          sortOrder: 90,
        ),
        req(
          id: 'ops_eng_ics200',
          name: 'ICS-200',
          description: 'Common ICS baseline for many agencies.',
          category: 'Command',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'ICS-200',
          sortOrder: 100,
        ),
        req(
          id: 'ops_eng_years_ff',
          name: 'Years as Firefighter',
          description: 'Many agencies prefer a minimum time riding before engineer responsibilities.',
          category: 'Experience',
          priority: RequirementPriority.recommended,
          type: RequirementType.experience,
          source: RequirementSource.recommended,
          experienceValue: 2,
          experienceUnit: 'years',
          departmentDependent: true,
          sortOrder: 110,
        ),
        req(
          id: 'ops_eng_drive_hours',
          name: 'Apparatus driving hours',
          description: 'Track driving time for your department’s qualification process.',
          category: 'Experience',
          priority: RequirementPriority.department,
          type: RequirementType.numericProgress,
          source: RequirementSource.departmentRequirement,
          progressRequired: 500,
          departmentDependent: true,
          sortOrder: 120,
        ),
        req(
          id: 'ops_eng_taskbook',
          name: 'Engineer task book',
          description: 'Department task book documenting engineer competencies.',
          category: 'Department',
          priority: RequirementPriority.department,
          type: RequirementType.taskBook,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 130,
        ),
        req(
          id: 'ops_eng_exam',
          name: 'Promotional written/practical exam',
          description: 'Many departments use a written exam and/or practical evaluation.',
          category: 'Department',
          priority: RequirementPriority.department,
          type: RequirementType.custom,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 140,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const ['fireops_calc', 'firepumpsim'],
      nextRoles: const ['Lieutenant', 'Captain'],
      createdAt: now,
      updatedAt: now,
    );

    final lieutenant = CareerGoal(
      id: 'ops_lieutenant',
      title: 'Lieutenant',
      category: 'Operations',
      description: 'Typical company officer preparation; department promotional processes vary.',
      subtitle: 'Engineer → Lieutenant',
      typicalPrerequisiteRoles: const ['Firefighter', 'Engineer / Driver Operator'],
      requirements: [
        req(
          id: 'ops_lt_ff2',
          name: 'Firefighter II',
          description: 'Common prerequisite for officer tracks.',
          category: 'Fire',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Firefighter II',
          sortOrder: 10,
        ),
        req(
          id: 'ops_lt_fo1',
          name: 'Fire Officer I',
          description: 'Common company officer certification.',
          category: 'Officer',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Fire Officer I',
          sortOrder: 20,
        ),
        req(
          id: 'ops_lt_fi1',
          name: 'Fire Instructor I',
          description: 'Often useful for officer development; may be required for training roles.',
          category: 'Instruction',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'Fire Instructor I',
          sortOrder: 30,
        ),
        req(
          id: 'ops_lt_ics200',
          name: 'ICS-200',
          description: 'Common ICS baseline before 300-level training.',
          category: 'Command',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'ICS-200',
          sortOrder: 40,
        ),
        req(
          id: 'ops_lt_ics300',
          name: 'ICS-300',
          description: 'Intermediate ICS; often used for officer roles.',
          category: 'Command',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          departmentDependent: true,
          certRef: 'ICS-300',
          sortOrder: 50,
        ),
        req(
          id: 'ops_lt_leadership',
          name: 'Leadership training',
          description: 'Company officer leadership and communication development.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 60,
        ),
        req(
          id: 'ops_lt_ic',
          name: 'Incident command training',
          description: 'Hands-on command simulations and tactical decision making.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 70,
        ),
        req(
          id: 'ops_lt_company_officer',
          name: 'Company officer training',
          description: 'Local policy, discipline, documentation, and operational expectations.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 80,
        ),
        req(
          id: 'ops_lt_report',
          name: 'Report writing & documentation',
          description: 'Improve narrative reports, documentation review, and QA processes.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 90,
        ),
        req(
          id: 'ops_lt_promo',
          name: 'Promotional process (exam/board/assessment)',
          description: 'Written exam, oral board, assessment center and/or task book, depending on your department.',
          category: 'Department',
          priority: RequirementPriority.department,
          type: RequirementType.custom,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 100,
        ),
        req(
          id: 'ops_lt_years',
          name: 'Minimum years of service',
          description: 'Many agencies have a minimum years-of-service or time-in-grade requirement.',
          category: 'Experience',
          priority: RequirementPriority.department,
          type: RequirementType.experience,
          source: RequirementSource.departmentRequirement,
          experienceValue: 3,
          experienceUnit: 'years',
          departmentDependent: true,
          sortOrder: 110,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['Captain', 'Battalion Chief'],
      createdAt: now,
      updatedAt: now,
    );

    final captain = CareerGoal(
      id: 'ops_captain',
      title: 'Captain',
      category: 'Operations',
      description: 'Advanced company officer development; requirements vary widely.',
      subtitle: 'Lieutenant → Captain',
      typicalPrerequisiteRoles: const ['Lieutenant'],
      requirements: [
        req(
          id: 'ops_cpt_fo2',
          name: 'Fire Officer II',
          description: 'Common for captain-level officer tracks.',
          category: 'Officer',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Fire Officer II',
          sortOrder: 10,
        ),
        req(
          id: 'ops_cpt_fi1',
          name: 'Fire Instructor I or II',
          description: 'Often beneficial for training management; department dependent.',
          category: 'Instruction',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          departmentDependent: true,
          sortOrder: 20,
        ),
        req(
          id: 'ops_cpt_ics300',
          name: 'ICS-300',
          description: 'Commonly required or expected for command responsibilities.',
          category: 'Command',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'ICS-300',
          sortOrder: 30,
        ),
        req(
          id: 'ops_cpt_ics400',
          name: 'ICS-400',
          description: 'Often recommended for higher-level incident management.',
          category: 'Command',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'ICS-400',
          sortOrder: 40,
        ),
        req(
          id: 'ops_cpt_admin',
          name: 'Administrative & personnel management',
          description: 'Evaluations, discipline, conflict resolution, and documentation.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 50,
        ),
        req(
          id: 'ops_cpt_budget',
          name: 'Budget basics',
          description: 'Budgeting and resource management fundamentals.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 60,
        ),
        req(
          id: 'ops_cpt_crr',
          name: 'Community risk reduction',
          description: 'Public education and prevention collaboration.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 70,
        ),
        req(
          id: 'ops_cpt_promo',
          name: 'Captain promotional process',
          description: 'Assessment center, promotional exam, and/or task book.',
          category: 'Department',
          priority: RequirementPriority.department,
          type: RequirementType.custom,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 80,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['Battalion Chief', 'Chief Officer'],
      createdAt: now,
      updatedAt: now,
    );

    final battalionChief = CareerGoal(
      id: 'ops_battalion_chief',
      title: 'Battalion Chief',
      category: 'Operations',
      description: 'Command and multi-company operations leadership; requirements vary.',
      subtitle: 'Captain → Battalion Chief',
      typicalPrerequisiteRoles: const ['Captain'],
      requirements: [
        req(
          id: 'ops_bc_fo3',
          name: 'Fire Officer III',
          description: 'Often recommended for chief officer tracks.',
          category: 'Officer',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'Fire Officer III',
          sortOrder: 10,
        ),
        req(
          id: 'ops_bc_ics300',
          name: 'ICS-300',
          description: 'Commonly expected before chief-level command.',
          category: 'Command',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'ICS-300',
          sortOrder: 20,
        ),
        req(
          id: 'ops_bc_ics400',
          name: 'ICS-400',
          description: 'Often expected for higher-level incident management.',
          category: 'Command',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'ICS-400',
          sortOrder: 30,
        ),
        req(
          id: 'ops_bc_multi',
          name: 'Multi-company operations training',
          description: 'Command simulations and complex incident management.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 40,
        ),
        req(
          id: 'ops_bc_em',
          name: 'Emergency management education',
          description: 'ICS, EOC concepts, continuity, and interagency coordination.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 50,
        ),
        req(
          id: 'ops_bc_dept_degree',
          name: "Bachelor's degree (if required)",
          description: 'Some departments require degrees; many do not.',
          category: 'Education',
          priority: RequirementPriority.department,
          type: RequirementType.custom,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 60,
        ),
        req(
          id: 'ops_bc_promo',
          name: 'Chief officer promotional assessment',
          description: 'Assessment center and executive leadership training vary by department.',
          category: 'Department',
          priority: RequirementPriority.department,
          type: RequirementType.custom,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 70,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['Chief Officer'],
      createdAt: now,
      updatedAt: now,
    );

    final chiefOfficer = CareerGoal(
      id: 'ops_chief_officer',
      title: 'Chief Officer',
      category: 'Operations',
      description: 'Executive leadership track; education and credentialing vary by agency.',
      subtitle: 'Battalion Chief → Chief Officer',
      typicalPrerequisiteRoles: const ['Battalion Chief', 'Captain'],
      requirements: [
        req(
          id: 'ops_co_fo3',
          name: 'Fire Officer III',
          description: 'Common for higher leadership tracks.',
          category: 'Officer',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'Fire Officer III',
          sortOrder: 10,
        ),
        req(
          id: 'ops_co_fo4',
          name: 'Fire Officer IV',
          description: 'Often recommended; not universal.',
          category: 'Officer',
          priority: RequirementPriority.development,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'Fire Officer IV',
          sortOrder: 20,
        ),
        req(
          id: 'ops_co_ics400',
          name: 'ICS-400',
          description: 'Commonly expected for command-level roles.',
          category: 'Command',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'ICS-400',
          sortOrder: 30,
        ),
        req(
          id: 'ops_co_exec',
          name: 'Executive leadership training',
          description: 'Strategic planning, leadership, and high-level decision making.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 40,
        ),
        req(
          id: 'ops_co_budget',
          name: 'Budgeting & finance',
          description: 'Budget development, purchasing, and financial stewardship.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 50,
        ),
        req(
          id: 'ops_co_labor',
          name: 'Labor relations & personnel management',
          description: 'HR fundamentals, labor relations, and personnel systems.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 60,
        ),
        req(
          id: 'ops_co_degree',
          name: 'Higher education (recommended or department dependent)',
          description: 'Some agencies prefer degrees; others prioritize experience and certifications.',
          category: 'Education',
          priority: RequirementPriority.department,
          type: RequirementType.custom,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 70,
        ),
        req(
          id: 'ops_co_crr',
          name: 'Community risk reduction',
          description: 'Prevention strategy, data-driven planning, and community programs.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 80,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const [],
      createdAt: now,
      updatedAt: now,
    );

    // EMS PATH
    final emt = CareerGoal(
      id: 'ems_emt',
      title: 'EMT',
      category: 'EMS',
      description: 'Baseline EMS provider credential; licensing varies by state.',
      subtitle: 'EMT → Advanced EMT → Paramedic',
      typicalPrerequisiteRoles: const [],
      requirements: [
        req(
          id: 'ems_emt_program',
          name: 'EMT education program',
          description: 'Complete an EMT course through an approved program.',
          category: 'Education',
          priority: RequirementPriority.core,
          type: RequirementType.trainingCourse,
          source: RequirementSource.commonlyRequired,
          sortOrder: 10,
        ),
        req(
          id: 'ems_emt_cpr',
          name: 'CPR/BLS',
          description: 'BLS credential required for most EMS roles.',
          category: 'Medical',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'CPR/BLS',
          sortOrder: 20,
        ),
        req(
          id: 'ems_emt_nremt',
          name: 'National Registry EMT (when applicable)',
          description: 'Some states use NREMT for initial or ongoing certification; others do not.',
          category: 'Licensure',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.stateRequirement,
          stateDependent: true,
          sortOrder: 30,
        ),
        req(
          id: 'ems_emt_state',
          name: 'State EMT certification/license',
          description: 'State licensure requirements vary; verify with your state EMS office.',
          category: 'Licensure',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.stateRequirement,
          stateDependent: true,
          sortOrder: 40,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['Advanced EMT', 'Paramedic'],
      createdAt: now,
      updatedAt: now,
    );

    final aemt = CareerGoal(
      id: 'ems_aemt',
      title: 'Advanced EMT',
      category: 'EMS',
      description: 'Advanced EMT availability and scope can be state dependent.',
      subtitle: 'EMT → Advanced EMT',
      typicalPrerequisiteRoles: const ['EMT'],
      requirements: [
        req(
          id: 'ems_aemt_current',
          name: 'Current EMT',
          description: 'Maintain EMT certification before advancing.',
          category: 'Licensure',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'EMT',
          sortOrder: 10,
        ),
        req(
          id: 'ems_aemt_program',
          name: 'AEMT education program',
          description: 'Complete an AEMT course through an approved program.',
          category: 'Education',
          priority: RequirementPriority.core,
          type: RequirementType.trainingCourse,
          source: RequirementSource.stateRequirement,
          stateDependent: true,
          sortOrder: 20,
        ),
        req(
          id: 'ems_aemt_nremt',
          name: 'National Registry AEMT (when applicable)',
          description: 'NREMT usage varies by state.',
          category: 'Licensure',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.stateRequirement,
          stateDependent: true,
          sortOrder: 30,
        ),
        req(
          id: 'ems_aemt_state',
          name: 'State AEMT certification/license',
          description: 'Verify your state’s AEMT requirements.',
          category: 'Licensure',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.stateRequirement,
          stateDependent: true,
          sortOrder: 40,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['Paramedic'],
      createdAt: now,
      updatedAt: now,
    );

    final paramedic = CareerGoal(
      id: 'ems_paramedic',
      title: 'Paramedic',
      category: 'EMS',
      description: 'Advanced EMS provider role; credentialing and protocols vary by state and agency.',
      subtitle: 'EMT → Paramedic',
      typicalPrerequisiteRoles: const ['EMT'],
      requirements: [
        req(
          id: 'ems_pm_emt',
          name: 'EMT',
          description: 'Baseline EMS certification.',
          category: 'Licensure',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'EMT',
          sortOrder: 10,
        ),
        req(
          id: 'ems_pm_program',
          name: 'Paramedic education program',
          description: 'Complete an accredited paramedic program.',
          category: 'Education',
          priority: RequirementPriority.core,
          type: RequirementType.trainingCourse,
          source: RequirementSource.commonlyRequired,
          sortOrder: 20,
        ),
        req(
          id: 'ems_pm_bls',
          name: 'CPR/BLS',
          description: 'BLS foundation for paramedic practice.',
          category: 'Medical',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'CPR/BLS',
          sortOrder: 30,
        ),
        req(
          id: 'ems_pm_acls',
          name: 'ACLS',
          description: 'Commonly required for paramedics in many systems.',
          category: 'Medical',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'ACLS',
          sortOrder: 40,
        ),
        req(
          id: 'ems_pm_pals',
          name: 'PALS',
          description: 'Commonly required for pediatric care readiness.',
          category: 'Medical',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'PALS',
          sortOrder: 50,
        ),
        req(
          id: 'ems_pm_nremt',
          name: 'National Registry Paramedic (when applicable)',
          description: 'Some states use NREMT for certification; varies.',
          category: 'Licensure',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.stateRequirement,
          stateDependent: true,
          sortOrder: 60,
        ),
        req(
          id: 'ems_pm_state',
          name: 'State paramedic certification/license',
          description: 'Verify with your state EMS office.',
          category: 'Licensure',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.stateRequirement,
          stateDependent: true,
          sortOrder: 70,
        ),
        req(
          id: 'ems_pm_optional',
          name: 'PHTLS / ITLS / AMLS / EPC (optional)',
          description: 'Often department dependent or specialty dependent; not universal.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          departmentDependent: true,
          sortOrder: 80,
        ),
        req(
          id: 'ems_pm_cc',
          name: 'Critical care education (optional)',
          description: 'Optional advanced education for critical care roles; varies by agency.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          departmentDependent: true,
          sortOrder: 90,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['EMS Supervisor'],
      createdAt: now,
      updatedAt: now,
    );

    final emsSupervisor = CareerGoal(
      id: 'ems_supervisor',
      title: 'EMS Supervisor',
      category: 'EMS',
      description: 'Leadership and quality improvement track; department processes vary.',
      subtitle: 'Paramedic → EMS Supervisor',
      typicalPrerequisiteRoles: const ['Paramedic'],
      requirements: [
        req(
          id: 'ems_sup_paramedic',
          name: 'Paramedic',
          description: 'Common prerequisite for EMS supervisory roles.',
          category: 'Licensure',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Paramedic',
          sortOrder: 10,
        ),
        req(
          id: 'ems_sup_years',
          name: 'Field experience',
          description: 'Minimum field time varies by department and system design.',
          category: 'Experience',
          priority: RequirementPriority.core,
          type: RequirementType.experience,
          source: RequirementSource.departmentRequirement,
          experienceValue: 3,
          experienceUnit: 'years',
          departmentDependent: true,
          sortOrder: 20,
        ),
        req(
          id: 'ems_sup_qi',
          name: 'Quality improvement training',
          description: 'Chart review, QA/QI, and clinical governance fundamentals.',
          category: 'Development',
          priority: RequirementPriority.recommended,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 30,
        ),
        req(
          id: 'ems_sup_ics200',
          name: 'ICS-200',
          description: 'Common ICS baseline.',
          category: 'Command',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'ICS-200',
          sortOrder: 40,
        ),
        req(
          id: 'ems_sup_ics300',
          name: 'ICS-300',
          description: 'Often recommended depending on system complexity.',
          category: 'Command',
          priority: RequirementPriority.development,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'ICS-300',
          sortOrder: 50,
        ),
        req(
          id: 'ems_sup_leadership',
          name: 'Leadership development',
          description: 'Coaching, conflict resolution, and documentation review.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 60,
        ),
        req(
          id: 'ems_sup_degree',
          name: 'Degree requirement (if required)',
          description: 'Some departments require degrees; others do not.',
          category: 'Education',
          priority: RequirementPriority.department,
          type: RequirementType.custom,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 70,
        ),
        req(
          id: 'ems_sup_taskbook',
          name: 'Supervisor task book / promotional exam',
          description: 'Promotional processes vary by department.',
          category: 'Department',
          priority: RequirementPriority.department,
          type: RequirementType.taskBook,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 80,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['EMS Captain / Chief'],
      createdAt: now,
      updatedAt: now,
    );

    // TRAINING PATH
    final fireInstructor = CareerGoal(
      id: 'training_instructor',
      title: 'Fire Instructor',
      category: 'Training',
      description: 'Instructor credentialing and expectations vary by agency and state.',
      subtitle: 'Firefighter → Instructor',
      typicalPrerequisiteRoles: const ['Firefighter'],
      requirements: [
        req(
          id: 'tr_fi1',
          name: 'Fire Instructor I',
          description: 'Baseline instructor credential.',
          category: 'Instruction',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Fire Instructor I',
          sortOrder: 10,
        ),
        req(
          id: 'tr_fi2',
          name: 'Fire Instructor II',
          description: 'Often recommended for lead instructor roles.',
          category: 'Instruction',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'Fire Instructor II',
          sortOrder: 20,
        ),
        req(
          id: 'tr_adult_ed',
          name: 'Adult education / lesson planning',
          description: 'Lesson planning, delivery, and evaluation skills.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 30,
        ),
        req(
          id: 'tr_skills_eval',
          name: 'Skills evaluation & testing',
          description: 'Performance evaluations, test development, and remediation.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 40,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['Training Officer', 'Training Captain / Chief'],
      createdAt: now,
      updatedAt: now,
    );

    final trainingOfficer = CareerGoal(
      id: 'training_officer',
      title: 'Training Officer',
      category: 'Training',
      description: 'Program management and documentation; requirements vary widely.',
      subtitle: 'Instructor → Training Officer',
      typicalPrerequisiteRoles: const ['Fire Instructor'],
      requirements: [
        req(
          id: 'tr_to_fi1',
          name: 'Fire Instructor I',
          description: 'Baseline instructor credential.',
          category: 'Instruction',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Fire Instructor I',
          sortOrder: 10,
        ),
        req(
          id: 'tr_to_fi2',
          name: 'Fire Instructor II (recommended)',
          description: 'Often helpful for program leadership.',
          category: 'Instruction',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'Fire Instructor II',
          sortOrder: 20,
        ),
        req(
          id: 'tr_to_fo1',
          name: 'Fire Officer I (recommended)',
          description: 'Common officer baseline for leadership and management.',
          category: 'Officer',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'Fire Officer I',
          sortOrder: 30,
        ),
        req(
          id: 'tr_to_curriculum',
          name: 'Curriculum development',
          description: 'Build programs, objectives, and evaluation tools.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 40,
        ),
        req(
          id: 'tr_to_docs',
          name: 'Training documentation & safety',
          description: 'Records management, compliance, and safety education.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 50,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['Training Captain / Chief'],
      createdAt: now,
      updatedAt: now,
    );

    // PREVENTION PATH
    final fireInspector = CareerGoal(
      id: 'prevention_inspector',
      title: 'Fire Inspector',
      category: 'Prevention',
      description: 'Inspection work varies by jurisdiction and code adoption.',
      subtitle: 'Firefighter → Inspector',
      typicalPrerequisiteRoles: const ['Firefighter'],
      requirements: [
        req(
          id: 'prev_fi1',
          name: 'Fire Inspector I',
          description: 'Common baseline inspector credential.',
          category: 'Prevention',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Fire Inspector I',
          sortOrder: 10,
        ),
        req(
          id: 'prev_code',
          name: 'Fire code education',
          description: 'Local code adoption and enforcement varies by state and jurisdiction.',
          category: 'Prevention',
          priority: RequirementPriority.core,
          type: RequirementType.trainingCourse,
          source: RequirementSource.stateRequirement,
          stateDependent: true,
          sortOrder: 20,
        ),
        req(
          id: 'prev_bldg',
          name: 'Building construction knowledge',
          description: 'Construction types, fire behavior, and protection systems.',
          category: 'Prevention',
          priority: RequirementPriority.recommended,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 30,
        ),
        req(
          id: 'prev_fi2',
          name: 'Fire Inspector II (recommended)',
          description: 'Often useful for advanced inspection responsibilities.',
          category: 'Prevention',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.recommended,
          certRef: 'Fire Inspector II',
          sortOrder: 40,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['Plans Examiner', 'Fire Marshal'],
      createdAt: now,
      updatedAt: now,
    );

    final plansExaminer = CareerGoal(
      id: 'prevention_plans',
      title: 'Plans Examiner',
      category: 'Prevention',
      description: 'Plans review and code application; credentialing varies by jurisdiction.',
      subtitle: 'Inspector → Plans Examiner',
      typicalPrerequisiteRoles: const ['Fire Inspector'],
      requirements: [
        req(
          id: 'prev_plans_cert',
          name: 'Plans Examiner certification (when used)',
          description: 'Not universal; depends on your jurisdiction and agency.',
          category: 'Prevention',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          certRef: 'Plans Examiner',
          sortOrder: 10,
        ),
        req(
          id: 'prev_plans_code',
          name: 'Building and fire code knowledge',
          description: 'Deep code familiarity across building/fire protection.',
          category: 'Prevention',
          priority: RequirementPriority.core,
          type: RequirementType.trainingCourse,
          source: RequirementSource.commonlyRequired,
          sortOrder: 20,
        ),
        req(
          id: 'prev_plans_spr',
          name: 'Sprinkler system knowledge',
          description: 'Design basics, components, and inspection/testing considerations.',
          category: 'Prevention',
          priority: RequirementPriority.recommended,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 30,
        ),
        req(
          id: 'prev_plans_alarm',
          name: 'Fire alarm knowledge',
          description: 'System components, monitoring, and code application.',
          category: 'Prevention',
          priority: RequirementPriority.recommended,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 40,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['Fire Marshal'],
      createdAt: now,
      updatedAt: now,
    );

    // INVESTIGATION PATH
    final investigator = CareerGoal(
      id: 'investigation_investigator',
      title: 'Fire Investigator',
      category: 'Investigation',
      description: 'Investigator credentialing varies; confirm local authority requirements.',
      subtitle: 'Firefighter → Fire Investigator',
      typicalPrerequisiteRoles: const ['Firefighter'],
      requirements: [
        req(
          id: 'inv_cert',
          name: 'Fire Investigator certification (when used)',
          description: 'Different certs exist; requirements vary by jurisdiction and agency.',
          category: 'Investigation',
          priority: RequirementPriority.recommended,
          type: RequirementType.certification,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          certRef: 'Fire Investigator',
          sortOrder: 10,
        ),
        req(
          id: 'inv_oc',
          name: 'Origin and cause fundamentals',
          description: 'Core knowledge for investigation work.',
          category: 'Investigation',
          priority: RequirementPriority.core,
          type: RequirementType.trainingCourse,
          source: RequirementSource.commonlyRequired,
          sortOrder: 20,
        ),
        req(
          id: 'inv_evidence',
          name: 'Evidence collection & documentation',
          description: 'Chain of custody, documentation, and scene safety.',
          category: 'Investigation',
          priority: RequirementPriority.core,
          type: RequirementType.trainingCourse,
          source: RequirementSource.commonlyRequired,
          sortOrder: 30,
        ),
        req(
          id: 'inv_interview',
          name: 'Interview techniques & legal considerations',
          description: 'Interviewing, report writing, and legal coordination.',
          category: 'Investigation',
          priority: RequirementPriority.recommended,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 40,
        ),
        req(
          id: 'inv_photos',
          name: 'Photography / scene documentation',
          description: 'Photo documentation, mapping, and evidence logs.',
          category: 'Investigation',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 50,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['Senior Investigator'],
      createdAt: now,
      updatedAt: now,
    );

    // HAZMAT PATH
    final hazmatTech = CareerGoal(
      id: 'hazmat_technician',
      title: 'HazMat Technician',
      category: 'HazMat',
      description: 'HazMat team roles vary by region, system design, and agency.',
      subtitle: 'HazMat Ops → Technician',
      typicalPrerequisiteRoles: const ['Firefighter'],
      requirements: [
        req(
          id: 'hz_ops',
          name: 'Hazardous Materials Operations',
          description: 'Baseline hazmat credential for many responders.',
          category: 'HazMat',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Hazardous Materials Operations',
          sortOrder: 10,
        ),
        req(
          id: 'hz_chem',
          name: 'Advanced chemistry & tox fundamentals',
          description: 'Chemistry, tox, and hazard recognition for technician roles.',
          category: 'HazMat',
          priority: RequirementPriority.recommended,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 20,
        ),
        req(
          id: 'hz_monitor',
          name: 'Monitoring equipment training',
          description: 'Meters, sampling, and interpretation.',
          category: 'HazMat',
          priority: RequirementPriority.recommended,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 30,
        ),
        req(
          id: 'hz_ppe',
          name: 'PPE & decontamination',
          description: 'PPE selection, limitations, and decon procedures.',
          category: 'HazMat',
          priority: RequirementPriority.core,
          type: RequirementType.trainingCourse,
          source: RequirementSource.commonlyRequired,
          sortOrder: 40,
        ),
        req(
          id: 'hz_leak',
          name: 'Leak control',
          description: 'Hands-on leak control operations and safety.',
          category: 'HazMat',
          priority: RequirementPriority.recommended,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 50,
        ),
        req(
          id: 'hz_ic',
          name: 'Incident command for HazMat',
          description: 'HazMat-specific incident management, zones, and risk assessment.',
          category: 'HazMat',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 60,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['HazMat Specialist / Team Leader'],
      createdAt: now,
      updatedAt: now,
    );

    // TECH RESCUE PATH (starter – future expansion)
    final techRescue = CareerGoal(
      id: 'rescue_tech',
      title: 'Technical Rescue (Specialties)',
      category: 'Technical Rescue',
      description: 'Specialty requirements vary by team and region. You can pursue one or multiple branches.',
      subtitle: 'Rope • Confined Space • Trench • Collapse • Machinery • Swiftwater',
      typicalPrerequisiteRoles: const ['Firefighter'],
      requirements: [
        req(
          id: 'tr_rope',
          name: 'Rope Rescue',
          description: 'Rope rescue awareness/operations/technician depending on your team.',
          category: 'Rescue',
          priority: RequirementPriority.recommended,
          type: RequirementType.trainingCourse,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 10,
        ),
        req(
          id: 'tr_confined',
          name: 'Confined Space Rescue',
          description: 'Confined space rescue training and team operations.',
          category: 'Rescue',
          priority: RequirementPriority.recommended,
          type: RequirementType.trainingCourse,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 20,
        ),
        req(
          id: 'tr_trench',
          name: 'Trench Rescue',
          description: 'Shoring, soil mechanics, and trench safety.',
          category: 'Rescue',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 30,
        ),
        req(
          id: 'tr_collapse',
          name: 'Structural Collapse',
          description: 'Collapse safety and operations training.',
          category: 'Rescue',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 40,
        ),
        req(
          id: 'tr_machinery',
          name: 'Vehicle / Machinery Rescue',
          description: 'Extrication, stabilization, and machinery rescue fundamentals.',
          category: 'Rescue',
          priority: RequirementPriority.recommended,
          type: RequirementType.trainingCourse,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 50,
        ),
        req(
          id: 'tr_swiftwater',
          name: 'Swiftwater Rescue',
          description: 'Water rescue operations and safety; availability varies by region.',
          category: 'Rescue',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 60,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const [],
      createdAt: now,
      updatedAt: now,
    );

    // FIRE PREVENTION – FIRE MARSHAL (starter)
    final fireMarshal = CareerGoal(
      id: 'prevention_marshal',
      title: 'Fire Marshal',
      category: 'Prevention',
      description: 'Executive-level prevention leadership; requirements vary by jurisdiction.',
      subtitle: 'Inspector/Plans → Fire Marshal',
      typicalPrerequisiteRoles: const ['Fire Inspector', 'Plans Examiner'],
      requirements: [
        req(
          id: 'marshal_prev_exp',
          name: 'Prevention leadership experience',
          description: 'Experience in inspections, plans review, and code enforcement leadership.',
          category: 'Experience',
          priority: RequirementPriority.recommended,
          type: RequirementType.experience,
          source: RequirementSource.departmentRequirement,
          experienceValue: 3,
          experienceUnit: 'years',
          departmentDependent: true,
          sortOrder: 10,
        ),
        req(
          id: 'marshal_management',
          name: 'Management & administration',
          description: 'Budgeting, personnel management, and program administration.',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 20,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const [],
      createdAt: now,
      updatedAt: now,
    );

    // EMS – EMS CAPTAIN/CHIEF (starter)
    final emsChief = CareerGoal(
      id: 'ems_chief',
      title: 'EMS Captain / EMS Chief',
      category: 'EMS',
      description: 'Senior EMS leadership; requirements vary by system design and agency.',
      subtitle: 'EMS Supervisor → EMS Captain/Chief',
      typicalPrerequisiteRoles: const ['EMS Supervisor', 'Paramedic'],
      requirements: [
        req(
          id: 'ems_chief_lead',
          name: 'Executive leadership & administration',
          description: 'Strategic planning, budgeting, clinical governance, and labor relations.',
          category: 'Leadership',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 10,
        ),
        req(
          id: 'ems_chief_degree',
          name: 'Degree requirement (if required)',
          description: 'Some agencies require degrees; many do not.',
          category: 'Education',
          priority: RequirementPriority.department,
          type: RequirementType.education,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 20,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const [],
      createdAt: now,
      updatedAt: now,
    );

    // TRAINING – TRAINING CAPTAIN/CHIEF (starter)
    final trainingChief = CareerGoal(
      id: 'training_chief',
      title: 'Training Captain / Training Chief',
      category: 'Training',
      description: 'Senior training program leadership; requirements vary by department.',
      subtitle: 'Training Officer → Training Chief',
      typicalPrerequisiteRoles: const ['Training Officer', 'Fire Instructor'],
      requirements: [
        req(
          id: 'tr_chief_admin',
          name: 'Training program management',
          description: 'Academy management, curriculum oversight, budgets, and compliance.',
          category: 'Leadership',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          sortOrder: 10,
        ),
        req(
          id: 'tr_chief_promo',
          name: 'Promotional process / assessment',
          description: 'Department promotional processes vary.',
          category: 'Department',
          priority: RequirementPriority.department,
          type: RequirementType.promotionalTest,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 20,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const [],
      createdAt: now,
      updatedAt: now,
    );

    // INVESTIGATION – SENIOR INVESTIGATOR (starter)
    final seniorInvestigator = CareerGoal(
      id: 'investigation_senior',
      title: 'Senior Fire Investigator',
      category: 'Investigation',
      description: 'Advanced investigation responsibilities; credentials vary by jurisdiction.',
      subtitle: 'Investigator → Senior Investigator',
      typicalPrerequisiteRoles: const ['Fire Investigator'],
      requirements: [
        req(
          id: 'inv_senior_training',
          name: 'Advanced investigation education',
          description: 'NFA, CFI-related education, and interagency coordination (as applicable).',
          category: 'Development',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          departmentDependent: true,
          sortOrder: 10,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const [],
      createdAt: now,
      updatedAt: now,
    );

    // HAZMAT – HAZMAT OPERATIONS (starter)
    final hazmatOps = CareerGoal(
      id: 'hazmat_ops',
      title: 'HazMat Operations',
      category: 'HazMat',
      description: 'Baseline HazMat Operations track; often part of firefighter requirements.',
      subtitle: 'Awareness → Operations → Technician',
      typicalPrerequisiteRoles: const ['Firefighter'],
      requirements: [
        req(
          id: 'hz_ops_awareness',
          name: 'Hazardous Materials Awareness',
          description: 'HazMat awareness baseline.',
          category: 'HazMat',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Hazardous Materials Awareness',
          sortOrder: 10,
        ),
        req(
          id: 'hz_ops_ops',
          name: 'Hazardous Materials Operations',
          description: 'Operations-level HazMat response training.',
          category: 'HazMat',
          priority: RequirementPriority.core,
          type: RequirementType.certification,
          source: RequirementSource.commonlyRequired,
          certRef: 'Hazardous Materials Operations',
          sortOrder: 20,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['HazMat Technician'],
      createdAt: now,
      updatedAt: now,
    );

    // WILDLAND PATH (general guidance)
    final wildland = CareerGoal(
      id: 'wildland',
      title: 'Wildland (General)',
      category: 'Wildland',
      description: 'General guidance only; agency-specific qualification systems vary widely.',
      subtitle: 'Wildland Firefighter → Engine Crew → Leadership',
      typicalPrerequisiteRoles: const [],
      requirements: [
        req(
          id: 'wl_basic',
          name: 'Wildland firefighter fundamentals',
          description: 'Basic wildland fire behavior, safety, and operations training.',
          category: 'Wildland',
          priority: RequirementPriority.core,
          type: RequirementType.trainingCourse,
          source: RequirementSource.departmentRequirement,
          departmentDependent: true,
          sortOrder: 10,
        ),
        req(
          id: 'wl_lead',
          name: 'Wildland leadership development',
          description: 'Progression to squad boss/engine boss/strike team roles varies by system.',
          category: 'Wildland',
          priority: RequirementPriority.development,
          type: RequirementType.trainingCourse,
          source: RequirementSource.recommended,
          departmentDependent: true,
          sortOrder: 20,
        ),
      ],
      recommendedExperience: const [],
      resourceIds: const [],
      nextRoles: const ['Engine Crew', 'Squad Boss', 'Engine Boss'],
      createdAt: now,
      updatedAt: now,
    );

    return [
      opsEntry,
      volunteerFirefighter,
      firefighter,
      careerFirefighter,
      engineer,
      lieutenant,
      captain,
      battalionChief,
      chiefOfficer,
      emt,
      aemt,
      paramedic,
      emsSupervisor,
      emsChief,
      fireInstructor,
      trainingOfficer,
      trainingChief,
      fireInspector,
      plansExaminer,
      fireMarshal,
      investigator,
      seniorInvestigator,
      hazmatOps,
      hazmatTech,
      techRescue,
      wildland,
    ];
  }

  static List<Resource> resources() {
    final now = DateTime.now();
    return [
      Resource(
        id: 'fireops_calc',
        title: 'FireOps Calc',
        description: 'Practice pump discharge pressure, friction loss, nozzle reaction, water supply, and fireground calculations.',
        type: ResourceType.fireOpsTool,
        url: 'https://fireops.app/calc',
        state: null,
        relatedCertificationIds: const ['Driver Operator – Pumper', 'Pump operations training'],
        relatedCareerGoalIds: const ['ops_engineer'],
        createdAt: now,
        updatedAt: now,
      ),
      Resource(
        id: 'firepumpsim',
        title: 'FirePumpSim',
        description: 'Practice pump operations through interactive pumping scenarios.',
        type: ResourceType.fireOpsTool,
        url: 'https://fireops.app/firepumpsim',
        state: null,
        relatedCertificationIds: const ['Driver Operator – Pumper', 'Pump operations training'],
        relatedCareerGoalIds: const ['ops_engineer'],
        createdAt: now,
        updatedAt: now,
      ),
      Resource(
        id: 'fireopssim',
        title: 'FireOpsSim',
        description: 'Interactive fireground simulation tools to build decision-making and operational skills.',
        type: ResourceType.fireOpsTool,
        url: 'https://fireops.app/fireopssim',
        state: null,
        relatedCertificationIds: const ['Firefighter I', 'Firefighter II'],
        relatedCareerGoalIds: const ['ops_firefighter'],
        createdAt: now,
        updatedAt: now,
      ),
      Resource(
        id: 'nims_ics',
        title: 'FEMA ICS / NIMS Courses',
        description: 'Common online ICS/NIMS courses (ICS-100/200/700/800). Verify your department’s accepted versions.',
        type: ResourceType.officialAgency,
        url: 'https://training.fema.gov/is/',
        state: null,
        relatedCertificationIds: const ['ICS-100', 'ICS-200', 'IS-700', 'IS-800'],
        relatedCareerGoalIds: const ['ops_firefighter', 'ops_engineer', 'ops_lieutenant'],
        createdAt: now,
        updatedAt: now,
      ),
      Resource(
        id: 'nremt',
        title: 'National Registry (NREMT)',
        description: 'NREMT testing and certification information (state usage varies).',
        type: ResourceType.officialAgency,
        url: 'https://www.nremt.org/',
        state: null,
        relatedCertificationIds: const ['National Registry EMT (when applicable)', 'National Registry Paramedic (when applicable)'],
        relatedCareerGoalIds: const ['ems_emt', 'ems_paramedic'],
        createdAt: now,
        updatedAt: now,
      ),
    ];
  }
}
