import 'package:firepath/models/requirement.dart';
import 'package:firepath/models/task_book.dart';

class Firefighter1CertificationGuideData {
  final String certificationId;
  final String title;
  final String summary;
  final List<String> pathwaySteps;
  final String officialSourceNote;
  final List<TaskBookTaskDefinition> tasks;

  const Firefighter1CertificationGuideData({
    required this.certificationId,
    required this.title,
    required this.summary,
    required this.pathwaySteps,
    required this.officialSourceNote,
    required this.tasks,
  });

  static Firefighter1CertificationGuideData? forRequirement(Requirement requirement) {
    final id = requirement.certificationDefinitionId;
    if (id == 'firefighter_1') return firefighterI;
    final name = requirement.name.trim().toLowerCase();
    if (name == 'firefighter i' || name == 'fire fighter i' || name == 'firefighter 1' || name == 'fire fighter 1' || name == 'ff1' || name == 'ffi') {
      return firefighterI;
    }
    return null;
  }

  static const firefighterI = Firefighter1CertificationGuideData(
    certificationId: 'firefighter_1',
    title: 'Firefighter I',
    summary: 'Use this mini task book to organize the full Firefighter I path from entry requirements through academy training, practical/JPR preparation, testing, certification, and local department qualification. Career Road explains what to work on; current state, academy, testing-agency, and department materials remain the official standard.',
    pathwaySteps: [
      'Confirm entry requirements and prerequisites',
      'Identify the approved Firefighter I academy/certification pathway',
      'Obtain the current official practical/JPR skill sheets',
      'Complete classroom, hands-on, and required live-fire instruction',
      'Practice core firefighter skills until performance is safe and consistent',
      'Complete required written and practical evaluations',
      'Receive the credential and complete local qualification steps',
      'Add Firefighter I to Career Road',
    ],
    officialSourceNote: 'These are original preparation categories, not copied official JPR wording. Verify current eligibility, live-fire prerequisites, evaluator sheets, testing rules, PPE requirements, and passing criteria with the state, academy, testing agency, and department that apply to you.',
    tasks: [
      TaskBookTaskDefinition(id: 'ff1_confirm_entry', title: 'Confirm Firefighter I entry requirements', section: 'GETTING STARTED', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Verify the entry requirements that apply before beginning Firefighter I training.', whatToKnow: ['Requirements vary by jurisdiction and academy.', 'Some pathways require affiliation, medical clearance, CPR/first aid, Hazardous Materials training, ICS courses, or other prerequisites.'], performanceTasks: ['Check the current eligibility requirements for the authority that will issue or recognize the credential.', 'Compare prerequisites with your Certifications and Career Record.', 'Add department-only prerequisites as custom tasks.'], safetyPoints: [], commonMistakes: ['Assuming every academy or online course leads to a credential recognized by your department or state.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_choose_path', title: 'Identify the approved Firefighter I pathway', section: 'GETTING STARTED', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Know who provides training, who tests, and who issues or recognizes the credential.', whatToKnow: ['Training provider, testing agency, state certification, and local department qualification may be separate processes.'], performanceTasks: ['Save the current official certification/candidate page.', 'Identify the approved academy/course and testing process.', 'Confirm how passing the process becomes an issued credential.'], safetyPoints: [], commonMistakes: ['Starting a course before confirming it satisfies the pathway you need.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_get_skill_sheets', title: 'Get current Firefighter I practical/JPR sheets', section: 'GETTING STARTED', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Use current official evaluation material as the final standard for hands-on preparation.', whatToKnow: ['Practical sheets and evaluator criteria can change.', 'Career Road organizes preparation but does not replace official evaluator material.'], performanceTasks: ['Obtain the current Firefighter I practical/JPR packet.', 'Confirm its revision/effective date.', 'Keep it available during skills practice.'], safetyPoints: [], commonMistakes: ['Practicing from an old skill sheet without checking the current revision.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_complete_instruction', title: 'Complete required Firefighter I instruction', section: 'TRAINING', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Complete required classroom, lab, academy, and supervised hands-on instruction.', whatToKnow: ['Course hours, attendance, assignments, testing sequence, and live-fire prerequisites vary.'], performanceTasks: ['Enroll in the approved Firefighter I program.', 'Complete required classroom and hands-on training.', 'Retain completion and attendance documentation.'], safetyPoints: ['Hands-on evolutions must follow academy/department safety controls and qualified instructor supervision.'], commonMistakes: ['Tracking only the final exam and forgetting required course documentation.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_live_fire', title: 'Complete required live-fire training', section: 'TRAINING', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Complete any required live-fire training under the approved standard and instructor controls.', whatToKnow: ['Exact live-fire prerequisites and safety rules come from the current academy/state/department program.'], performanceTasks: ['Confirm whether live-fire participation is required.', 'Complete all prerequisites before participation.', 'Complete required live-fire evolutions and retain documentation.'], safetyPoints: ['Never recreate certification live-fire evolutions outside an approved program with qualified instructors and required safety controls.'], commonMistakes: ['Treating informal department drills as interchangeable with required certification documentation.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_ppe_scba', title: 'PPE, SCBA, and emergency procedures', section: 'PRACTICAL / JPR PREPARATION', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Build reliable PPE/SCBA inspection, donning, use, air-management, and emergency habits.', whatToKnow: ['PPE/SCBA components, inspection points, donning expectations, PASS operation, emergency procedures, and air management.'], performanceTasks: ['Inspect PPE and SCBA.', 'Don PPE and SCBA using the required method.', 'Operate in SCBA while performing basic firefighter tasks.', 'Practice local emergency procedures in a controlled training environment.'], safetyPoints: ['Use qualified instructors for restricted-visibility, confidence, entanglement, and emergency SCBA evolutions.'], commonMistakes: ['Treating donning speed as more important than full PPE closure and function checks.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_fire_behavior', title: 'Fire behavior and tactical awareness', section: 'PRACTICAL / JPR PREPARATION', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Recognize basic fire behavior, smoke/flow-path indicators, changing conditions, and hazards.', whatToKnow: ['Combustion, heat transfer, fire development, smoke indicators, ventilation effects, flow path, and rapidly changing conditions.'], performanceTasks: ['Identify fire/smoke indicators from training media.', 'Explain how openings may change conditions.', 'Identify when conditions should be communicated to the crew or command.'], safetyPoints: ['Classroom recognition does not replace instructor-led live-fire training.'], commonMistakes: ['Memorizing terminology without connecting observations to crew safety.'], practiceTools: [TaskBookPracticeToolLink(title: 'Practice in FireOpsSim', route: '/resources?tool=fireopssim', subtitle: 'Fire behavior and firefighter decision drills')], resources: []),
      TaskBookTaskDefinition(id: 'ff1_hose_nozzle', title: 'Hose, nozzle, and fire attack fundamentals', section: 'PRACTICAL / JPR PREPARATION', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Build safe, coordinated hose deployment, advancement, nozzle operation, and fire-attack fundamentals.', whatToKnow: ['Hose sizes, appliances, nozzle types, stream selection, hose loads, advancement, door control, and communication.'], performanceTasks: ['Deploy and advance common hose loads.', 'Operate the nozzle and demonstrate stream control.', 'Advance charged and uncharged lines as a crew.', 'Demonstrate hose maintenance and return-to-service.'], safetyPoints: ['Maintain crew coordination, control hose reaction, preserve egress, and follow live-fire safety rules.'], commonMistakes: ['Focusing on nozzle movement while losing crew communication or egress awareness.'], practiceTools: [TaskBookPracticeToolLink(title: 'Practice in FireOpsSim', route: '/resources?tool=fireopssim', subtitle: 'Fire attack and hose-line decision practice')], resources: []),
      TaskBookTaskDefinition(id: 'ff1_ladders', title: 'Ground ladder operations', section: 'PRACTICAL / JPR PREPARATION', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Safely select, carry, raise, place, climb, and lower ground ladders.', whatToKnow: ['Ladder types, parts, inspection points, carries, raises, placement, overhead hazards, climbing, and stowing.'], performanceTasks: ['Inspect/select the proper ladder.', 'Perform program-required carries and raises.', 'Place and climb using required safety practices.', 'Lower and return the ladder to service.'], safetyPoints: ['Survey electrical hazards, footing, traffic, openings, and personnel position before raising or climbing.'], commonMistakes: ['Rushing the raise and skipping hazard checks or crew communication.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_forcible_entry', title: 'Forcible entry and tool use', section: 'PRACTICAL / JPR PREPARATION', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Use common hand and power tools safely for basic access and forcible-entry assignments.', whatToKnow: ['Tool selection, inspection, striking zones, basic door/window construction, conventional entry concepts, and local power-tool safety.'], performanceTasks: ['Select/carry tools for a basic access problem.', 'Demonstrate conventional forcible-entry techniques on a training prop.', 'Operate assigned power tools under instructor supervision when included.'], safetyPoints: ['Maintain PPE, controlled striking zones, stable footing, and personnel awareness.'], commonMistakes: ['Using excessive force before reading the door, lock, hinge, and construction.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_search_rescue', title: 'Search, victim removal, and firefighter survival', section: 'PRACTICAL / JPR PREPARATION', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Practice organized search, orientation, victim movement, and basic firefighter emergency actions.', whatToKnow: ['Primary search concepts, orientation, victim movement, MAYDAY expectations, and local survival procedures.'], performanceTasks: ['Complete a structured search while maintaining crew contact/orientation.', 'Locate and move a simulated victim.', 'Communicate significant findings and search progress.', 'Practice local MAYDAY/emergency communication procedures.'], safetyPoints: ['Maintain crew integrity, air awareness, and instructor controls during low-visibility/survival evolutions.'], commonMistakes: ['Moving too fast and losing orientation, crew contact, or air awareness.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_ventilation', title: 'Basic ventilation operations', section: 'PRACTICAL / JPR PREPARATION', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Perform basic ventilation assignments as coordinated fireground actions.', whatToKnow: ['Horizontal, vertical, and mechanical ventilation; coordination with suppression; tools; and roof/window hazards.'], performanceTasks: ['Demonstrate ventilation methods included in your program.', 'Explain timing relative to attack/search.', 'Use common ventilation tools under instructor supervision.'], safetyPoints: ['Follow ladder, roof, saw, glass, fall, and live-fire controls.'], commonMistakes: ['Treating ventilation as an isolated skill instead of a coordinated tactical action.'], practiceTools: [TaskBookPracticeToolLink(title: 'Practice in FireOpsSim', route: '/resources?tool=fireopssim', subtitle: 'Ventilation timing and coordination practice')], resources: []),
      TaskBookTaskDefinition(id: 'ff1_water_supply', title: 'Water supply, hydrants, and basic appliances', section: 'PRACTICAL / JPR PREPARATION', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Perform basic water-supply assignments using hydrants, hose, appliances, and local procedures.', whatToKnow: ['Hydrant operation, supply hose, common appliances, supply-line deployment, and operator communication.'], performanceTasks: ['Connect to and operate a training hydrant.', 'Deploy supply hose and common appliances.', 'Communicate completion or water-supply problems.'], safetyPoints: ['Control traffic exposure, hose movement, hydrant caps, tools, and pressure changes.'], commonMistakes: ['Operating hydrants/appliances without confirming crew readiness and expected flow.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_salvage_overhaul', title: 'Salvage, overhaul, and property conservation', section: 'PRACTICAL / JPR PREPARATION', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Perform basic salvage and overhaul while continuing to manage hidden fire and scene hazards.', whatToKnow: ['Salvage covers, water control, overhaul tools, hidden-fire indicators, utilities, structure, and evidence preservation.'], performanceTasks: ['Deploy a salvage cover or water-control method.', 'Use common overhaul tools in training.', 'Identify likely hidden-fire locations and continuing hazards.'], safetyPoints: ['Do not reduce PPE, air-monitoring, structural, or utility awareness because visible fire is out.'], commonMistakes: ['Treating overhaul as a low-risk cleanup phase.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_ropes_knots', title: 'Ropes, knots, and tool hoisting', section: 'PRACTICAL / JPR PREPARATION', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Tie and apply program-required knots and basic equipment-hoisting methods.', whatToKnow: ['Life-safety vs utility rope, inspection, knot purpose, dressing/setting, and basic hoisting.'], performanceTasks: ['Tie each required knot and identify its purpose.', 'Inspect rope for damage.', 'Secure and hoist common tools/equipment using the approved method.'], safetyPoints: ['Do not treat basic knot practice as technical-rescue authorization.'], commonMistakes: ['Memorizing knot motions without understanding loading, dressing, security, and purpose.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_extinguishers', title: 'Portable extinguishers', section: 'PRACTICAL / JPR PREPARATION', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Select and operate an appropriate extinguisher for a small controllable fire while maintaining an exit.', whatToKnow: ['Fire classifications, extinguisher types, limitations, inspection points, and escape considerations.'], performanceTasks: ['Select an extinguisher for a training scenario.', 'Inspect and operate it using the taught method.', 'State when extinguisher use should stop and withdrawal is required.'], safetyPoints: ['Maintain an exit path and remain within training scope.'], commonMistakes: ['Choosing an extinguisher based only on size instead of fuel/fire class and conditions.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_scene_comms', title: 'Communications, accountability, and incident operations', section: 'PRACTICAL / JPR PREPARATION', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Receive assignments, maintain accountability, and communicate hazards/progress clearly within incident command.', whatToKnow: ['Basic ICS terminology, radio procedure, accountability, emergency traffic/MAYDAY, and assignment confirmation.'], performanceTasks: ['Receive and repeat back an assignment.', 'Give a concise progress or hazard report.', 'Demonstrate local accountability during a drill.'], safetyPoints: ['Radio communication does not replace crew integrity or direct accountability.'], commonMistakes: ['Long or unclear radio traffic that hides the critical message.'], practiceTools: [TaskBookPracticeToolLink(title: 'Practice in FireOpsSim', route: '/resources?tool=fireopssim', subtitle: 'Radio, accountability, and basic incident decision practice')], resources: []),
      TaskBookTaskDefinition(id: 'ff1_written_prep', title: 'Prepare for the Firefighter I knowledge evaluation', section: 'TESTING', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Prepare from current official candidate information and course objectives.', whatToKnow: ['Exam format, passing score, retest rules, references, and testing-day requirements vary.'], performanceTasks: ['Confirm current testing rules/objectives.', 'Build a study plan around weak areas.', 'Use practice questions as study tools, not as the official blueprint.'], safetyPoints: [], commonMistakes: ['Studying only random question banks instead of current official objectives.'], practiceTools: [TaskBookPracticeToolLink(title: 'Practice in FireOpsSim', route: '/resources?tool=fireopssim', subtitle: 'Firefighter I knowledge and scenario review')], resources: []),
      TaskBookTaskDefinition(id: 'ff1_practical_prep', title: 'Prepare for the Firefighter I practical/JPR evaluation', section: 'TESTING', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Turn the official practical packet into a station-by-station practice plan.', whatToKnow: ['Only current official evaluator material defines stations, critical failures, safety criteria, and passing standards.'], performanceTasks: ['Practice every official station with qualified instructors/evaluators.', 'Repeat weak stations until performance is consistent.', 'Complete at least one full mock practical using expected PPE/equipment.'], safetyPoints: ['Use approved controls for ladders, power tools, SCBA confidence, live fire, and other higher-risk skills.'], commonMistakes: ['Memorizing a checklist without understanding objectives and safety points.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_complete_testing', title: 'Complete required Firefighter I testing', section: 'TESTING', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Complete required knowledge and practical evaluation components through the correct authority.', whatToKnow: [], performanceTasks: ['Register for all required components.', 'Complete written/knowledge and practical evaluations.', 'Save official results/completion documents.'], safetyPoints: [], commonMistakes: ['Assuming academy graduation automatically means the credential is issued.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_issue_credential', title: 'Complete certification issuance steps', section: 'CERTIFICATION', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Finish any application, affiliation, document, fee, or verification step needed for formal issuance.', whatToKnow: ['Some systems issue automatically; others require post-test paperwork or department verification.'], performanceTasks: ['Confirm post-test requirements.', 'Submit required documentation.', 'Verify Firefighter I is formally issued/recorded.'], safetyPoints: [], commonMistakes: ['Stopping after passing tests without confirming formal issuance.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_department_qualification', title: 'Complete department-specific firefighter qualification', section: 'CERTIFICATION', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Separate certification from local probationary, apparatus, policy, EMS, station, or task-book requirements.', whatToKnow: ['A Firefighter I certificate may be only one part of local firefighter qualification.'], performanceTasks: ['Review local probationary/task-book requirements.', 'Complete local sign-offs/orientation not included in Firefighter I.', 'Add department-only items to Career Road when useful.'], safetyPoints: [], commonMistakes: ['Treating certification as automatic clearance for every department assignment.'], practiceTools: [], resources: []),
      TaskBookTaskDefinition(id: 'ff1_add_credential', title: 'Add Firefighter I credential to Career Road', section: 'CERTIFICATION', goalId: null, requirementId: null, isCustom: false, fireOpsObjective: 'Save the issued credential so later career goals recognize Firefighter I as complete.', whatToKnow: ['Store the issuing authority, issue/expiration information when applicable, and supporting documentation.'], performanceTasks: ['Add Firefighter I in Certifications.', 'Confirm it matches the active Firefighter I requirement.', 'Retain evidence for promotion, transfer, or renewal needs.'], safetyPoints: [], commonMistakes: ['Not adding the issued credential, causing later Roadmap steps to show Firefighter I as missing.'], practiceTools: [], resources: []),
    ],
  );
}
